import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const css = await readFile(new URL('../css/app.css', import.meta.url), 'utf8');
const manifest = await readFile(new URL('../manifest.webmanifest', import.meta.url), 'utf8');

const workspaceStart = html.indexOf('id="projectBuilder"');
const estimateStart = html.indexOf('class="project-subdetails estimate-details"');
const actualStart = html.indexOf('class="project-subdetails actual-details"');
const comparisonStart = html.indexOf('class="comparison-box"');
const completionButton = html.indexOf('id="completeProject"');
const workspaceEnd = html.indexOf('</section>', workspaceStart);

assert.ok(workspaceStart >= 0, 'project workspace exists');
assert.ok(estimateStart > workspaceStart, 'estimate is inside the project workspace');
assert.ok(actualStart > estimateStart, 'actual expenses follow the estimate');
assert.ok(comparisonStart > actualStart, 'plan-to-actual comparison is inside actual expenses');
assert.ok(completionButton > comparisonStart, 'completion action follows actual expenses and comparison');
assert.ok(completionButton < workspaceEnd, 'completion action stays inside the project workspace');
assert.equal((html.match(/id="completeProject"/g) || []).length, 1, 'completion action is unique');
assert.match(html, /id="projectHistory" class="project-history"/, 'project library is a separate disclosure');
assert.match(html, /id="projects" class="card project-card view-panel/, 'Android shell can navigate directly to projects');
assert.match(html, /id="projectPrivateContent">/, 'project workspace is available without authorization');
assert.doesNotMatch(html.slice(workspaceStart, workspaceEnd), /id="authForm"/, 'owner sign-in is absent from the projects workspace');
assert.match(html, /id="ownerAccessToggle" class="cloud-access-toggle"/, 'owner sign-in opens from a compact cloud button');
assert.match(html, /id="ownerAccessPanel" class="cloud-auth-panel hidden"/, 'cloud authorization panel is hidden by default');
assert.match(html, /placeholder="Например: Проект 1"/, 'new project dialog uses a neutral example name');
assert.match(html, /Без входа проекты сохраняются в этом браузере/, 'public projects explain local browser storage');
assert.match(html, /id="actualExpenses" class="project-subdetails actual-details"/, 'Android shell can navigate directly to actual expenses');
assert.match(html, /class="app-tab active"[^>]*data-app-view="calculator"/, 'calculator has a primary navigation tab');
assert.match(html, /data-app-view="projects"/, 'projects have a primary navigation tab');
assert.match(html, /data-app-view="tariffs"/, 'tariffs have a primary navigation tab');
assert.match(html, /data-provider="dreamina"/, 'Dreamina has a calculator provider tab');
assert.match(html, /class="provider-tab provider-tab-plus provider-plus-standalone hidden"[^>]*data-provider="dreamina-plus"[^>]*data-private-provider="dreamina-plus"/, 'Dreamina Plus is a standalone button hidden before owner authorization');
assert.match(html, /class="provider-tabs"[^>]*aria-label="Публичные провайдеры генерации"[\s\S]*data-provider="kling"[\s\S]*data-provider="syntex"[\s\S]*data-provider="dreamina"[\s\S]*<\/div>\s*<button class="provider-tab provider-tab-plus provider-plus-standalone hidden"/, 'public provider plate contains exactly the three public services before the standalone Plus button');
assert.match(html, /id="dreaminaPackagePreset"/, 'Dreamina offers selectable official package presets');
assert.match(html, /value="basic-monthly">Basic · 15 \$ · 1 575 кредитов/, 'Dreamina Basic monthly package is the first official preset');
assert.match(html, /value="standard-monthly">Standard · 36 \$ · 3 885 кредитов/, 'Dreamina Standard uses the published USD package price');
assert.match(html, /value="advanced-monthly">Advanced · 79 \$ · 8 645 кредитов/, 'Dreamina Advanced uses the published USD package price');
assert.doesNotMatch(html, /169 SEK|basic-quarterly|basic-yearly|basic-one-month/, 'Dreamina presets contain no inferred SEK conversions');
assert.doesNotMatch(html, /Pro · месяц|Max · месяц/, 'obsolete promotional Dreamina package names are removed');
assert.match(html, /class="subcard dreamina-plus-card hidden"[^>]*data-private-provider="dreamina-plus"/, 'Dreamina Plus tariff card is hidden before owner authorization');
assert.match(html, /100 ₽ <span>за<\/span> 10 500 токенов/, 'Dreamina Plus fixed exchange remains in the public application source');
assert.match(manifest, /pwa-logo-v5-192\.png/, 'PWA uses the original full-size 192px logo');
assert.match(manifest, /pwa-logo-v5-512\.png/, 'PWA uses the original full-size 512px logo');
assert.doesNotMatch(manifest, /"purpose": "maskable"/, 'tablet cannot substitute a padded or haloed maskable logo');
assert.doesNotMatch(manifest, /"orientation":\s*"portrait-primary"/, 'PWA is not locked to portrait orientation');
assert.match(manifest, /"orientation":\s*"any"/, 'PWA explicitly allows portrait and landscape orientations');
assert.match(html, /id="closeProject"/, 'opened project can be closed back to its list');
assert.match(html, /id="newProjectFromWorkspace"/, 'another project can be created without completing the open one');
assert.match(html, /id="closeProject"[^>]*>Свернуть</, 'active project can be folded without completion');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /next === 'projects' && activeProject\(\)/, 'opening the projects tab folds any previously open workspace');
assert.match(html, /id="customQuotedPrice"/, 'project can use a custom quoted price');
assert.match(html, /id="workPriceResult"/, 'customer price has a dedicated visible result area');
assert.match(html, /id="priceRounding"/, 'project price supports rounding');
assert.match(html, /id="manualTariffProvider"/, 'manual tariff editor has a provider selector');
assert.match(html, /id="manualTariffModel"/, 'manual tariff editor has a model selector');
assert.match(html, /id="manualTariffVariant"/, 'manual tariff editor has a mode selector');
assert.match(html, /id="manualTariffDuration"/, 'manual tariff editor has a duration selector');
assert.match(html, /id="manualTariffTokens"/, 'manual tariff editor records token spending');
assert.match(html, /тарифы синхронизируются с личным облаком/, 'manual tariffs describe cross-device cloud sync');
assert.match(html, /id="saveManualTariff"/, 'manual tariff editor can save an exact-duration token tariff');
assert.match(html, /id="baseTariffDate"/, 'manual tariff editor shows the base tariff date');
assert.match(html, /id="resetManualTariffs"/, 'manual tariff overrides can be reset to the base tariff table');
assert.match(html, /id="compareCalculatorSyntex"/, 'single-generation result can be compared with SYNTX');
assert.match(html, /id="compareEstimateSyntex"/, 'project estimate can be compared with SYNTX');
assert.match(html, /id="compareActualSyntex"/, 'actual project cost can be compared with SYNTX');
assert.match(css, /\.project-workspace\s*\{/, 'active project has a distinct visual workspace');
assert.match(css, /\.project-completion-panel\s*\{/, 'completion has a dedicated visual panel');
assert.match(css, /\.app-tabs\s*\{/, 'primary navigation is styled');
assert.match(css, /\.stepper\s*\{/, 'quantity stepper is styled');
assert.match(css, /\.manual-tariff-editor\s*\{/, 'manual tariff editor is styled');
assert.match(css, /\.provider-tabs\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/, 'public provider plate always has three columns');
assert.doesNotMatch(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /стоимость зафиксирована при записи/, 'actual generation rows do not repeat verbose fixed-cost text');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /orientation\?\.unlock/, 'PWA releases an orientation lock left by an older installation');
assert.match(await readFile(new URL('../css/v3.css', import.meta.url), 'utf8'), /\.project-workspace\{margin:14px 0 0;padding:0;overflow:visible;border:0/, 'mobile project workspace does not waste width on nested frames');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /class="actual-action actual-repeat"[^>]*title="Повторить"/, 'each actual generation has a compact repeat action');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /class="actual-action actual-remove"[^>]*title="Удалить"/, 'repeat and delete use the same action-button component');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /actualItems\.push\(\{[\s\S]*JSON\.parse\(JSON\.stringify\(source\)\)/, 'repeat action copies the recorded generation snapshot');
assert.doesNotMatch(css, /\.actual-repeat:hover[^}]*rotate/, 'repeat button does not use a spinning hover animation');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /visibilitychange[\s\S]*refreshProjectsOnForeground/, 'projects refresh when the PWA returns to the foreground');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /clearTimeout\(projectSyncTimers\.get\(project\.id\)\)/, 'completion cancels a pending stale autosave');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /provider !== PRIVATE_PROVIDER_ID \|\| Boolean\(cloudSession\)/, 'Dreamina Plus requires an authenticated owner session');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /if \(!canUseProvider\(provider\)\) return \[\]/, 'private provider models cannot be used by anonymous calculator calls');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /refreshProviderAccess\(\)/, 'provider visibility refreshes with authorization state');
assert.doesNotMatch(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /variants\.filter\(variant => variant\.billing\?\.type === 'manual_required'\)/, 'built-in SYNTX tariffs can be overridden in the manual editor');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /unitsByDuration:/, 'manual tariff overrides are stored for an exact duration');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /function syntexEquivalent\(/, 'provider models are mapped to exact SYNTX equivalents');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /syntexCompareMarkup\('project-syntex-compare'\)/, 'each project estimate line has a SYNTX comparison');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /syntexCompareMarkup\('actual-syntex-compare'\)/, 'each recorded generation has a SYNTX comparison');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /switchProjectLibrary\(session \? 'owner' : 'guest'\)/, 'authorization switches between isolated owner and guest libraries');

console.log('UI structure tests OK');
