import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const css = await readFile(new URL('../css/app.css', import.meta.url), 'utf8');
const manifest = await readFile(new URL('../manifest.webmanifest', import.meta.url), 'utf8');

const workspaceStart = html.indexOf('id="projectBuilder"');
const estimateStart = html.indexOf('class="project-subdetails estimate-details"');
const actualStart = html.indexOf('class="project-subdetails actual-details"');
const comparisonStart = html.indexOf('class="comparison-box"');
const completionButton = html.indexOf('id="completeProject"');
const workspaceEnd = html.indexOf('</section>', workspaceStart);

assert.ok(workspaceStart >= 0, 'project workspace exists');
assert.ok(estimateStart > workspaceStart, 'estimate is inside the project workspace');
assert.ok(actualStart > estimateStart, 'actual expenses follow the estimate');
assert.ok(comparisonStart > actualStart, 'plan-to-actual comparison is inside actual expenses');
assert.ok(completionButton > comparisonStart, 'completion action follows actual expenses and comparison');
assert.ok(completionButton < workspaceEnd, 'completion action stays inside the project workspace');
assert.equal((html.match(/id="completeProject"/g) || []).length, 1, 'completion action is unique');
assert.match(html, /id="projectHistory" class="project-history"/, 'project library is a separate disclosure');
assert.match(html, /id="projects" class="card project-card view-panel/, 'Android shell can navigate directly to projects');
assert.match(html, /id="actualExpenses" class="project-subdetails actual-details"/, 'Android shell can navigate directly to actual expenses');
assert.match(html, /class="app-tab active"[^>]*data-app-view="calculator"/, 'calculator has a primary navigation tab');
assert.match(html, /data-app-view="projects"/, 'projects have a primary navigation tab');
assert.match(html, /data-app-view="tariffs"/, 'tariffs have a primary navigation tab');
assert.match(manifest, /pwa-logo-v3-192\.png/, 'PWA uses the current 192px logo');
assert.match(manifest, /pwa-logo-v3-512\.png/, 'PWA uses the current 512px logo');
assert.match(manifest, /pwa-logo-v3-maskable-512\.png/, 'PWA has a padded Android maskable logo');
assert.match(manifest, /"purpose": "maskable"/, 'Android maskable icon is declared separately');
assert.match(html, /id="closeProject"/, 'opened project can be closed back to its list');
assert.match(html, /id="newProjectFromWorkspace"/, 'another project can be created without completing the open one');
assert.match(html, /id="closeProject"[^>]*>Свернуть</, 'active project can be folded without completion');
assert.match(await readFile(new URL('../js/app.js', import.meta.url), 'utf8'), /next === 'projects' && activeProject\(\)/, 'opening the projects tab folds any previously open workspace');
assert.match(html, /id="customQuotedPrice"/, 'project can use a custom quoted price');
assert.match(html, /id="workPriceResult"/, 'customer price has a dedicated visible result area');
assert.match(html, /id="priceRounding"/, 'project price supports rounding');
assert.match(html, /id="manualTariffProvider"/, 'manual tariff editor has a provider selector');
assert.match(html, /id="manualTariffModel"/, 'manual tariff editor has a model selector');
assert.match(html, /id="manualTariffVariant"/, 'manual tariff editor has a mode selector');
assert.match(html, /id="manualTariffDuration"/, 'manual tariff editor has a duration selector');
assert.match(html, /id="manualTariffTokens"/, 'manual tariff editor records token spending');
assert.match(html, /тарифы синхронизируются с личным облаком/, 'manual tariffs describe cross-device cloud sync');
assert.match(html, /id="saveManualTariff"/, 'manual tariff editor can save a per-second token rate');
assert.match(css, /\.project-workspace\s*\{/, 'active project has a distinct visual workspace');
assert.match(css, /\.project-completion-panel\s*\{/, 'completion has a dedicated visual panel');
assert.match(css, /\.app-tabs\s*\{/, 'primary navigation is styled');
assert.match(css, /\.stepper\s*\{/, 'quantity stepper is styled');
assert.match(css, /\.manual-tariff-editor\s*\{/, 'manual tariff editor is styled');

console.log('UI structure tests OK');
